# Configure all environments according to your file at ~/.aws/config
# list of configured profiles
accounts:
  - account1
  - account2

# definition of filters and sort criteria can be found here:
# https://docs.aws.amazon.com/cli/latest/reference/securityhub/get-findings.html

# filters to be used to filter for security findints
filters:
  - filter_name: state
    value: ACTIVE
    comparison: '='